[mypy]
# Ignore les erreurs sur les bibliothèques tierces
ignore_missing_imports = True

# Ne pas être trop strict sur les types manquants
disallow_untyped_defs = False
disallow_incomplete_defs = False

# Autoriser les valeurs None par défaut (règle les erreurs "implicit Optional")
no_implicit_optional = False

# Désactiver les erreurs de vérification de corps de fonctions non typées
check_untyped_defs = False

# Désactiver les vérifications strictes sur les erreurs d'assignation
disable_error_code = attr-defined,arg-type,assignment,operator,call-overload
